# Generated by Django 2.0.5 on 2018-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='temp notes', max_length=255),
            preserve_default=False,
        ),
    ]
